services:
  - type: web
    name: will-smith-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: GUILD_ID
        sync: false
      - key: LOL_KEY
        sync: false
      - key: NODE_ENV
        value: production

