name: CI

on:
  push:
    branches: [main]

jobs:
  DockerImage:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4.1.2

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with: 
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: yuribatista/will-smith:latest
